FROM osrf/ros:noetic-desktop-full

SHELL [ "/bin/bash" , "-c" ]

RUN apt-get update && apt-get install -y git pip nano build-essential 

RUN pip install --upgrade pip

RUN source /opt/ros/noetic/setup.bash \
 && mkdir -p ./hello_turtle_ws/src \
 && cd ./hello_turtle_ws/src \
 && catkin_init_workspace \
 && git clone https://github.com/Nguiom/hello_turtle.git

RUN source /opt/ros/noetic/setup.bash \
 && cd ./hello_turtle_ws \
 && catkin_make
RUN echo "source /hello_turtle_ws/devel/setup.bash" >> ~/.bashrc

WORKDIR /hello_turtle_ws
