FROM osrf/ros:noetic-desktop-full

SHELL [ "/bin/bash" , "-c" ]

RUN apt-get update && apt-get install -y git pip nano build-essential 

RUN pip install --upgrade pip

RUN source /opt/ros/noetic/setup.bash \
 && git clone https://github.com/Nguiom/Laboratorio_robotica.git